#!/usr/bin/env python3

# This was a bad socket handling vulnerability.
# When we closed the socket, we incorrectly assumed that the socket would still be open for us to close.
# Due to this, the program would panic if a socket was already closed by the time we tried to close it.

import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("localhost", 8080))
s.close()

print("Server has been crashed if it was vulnerable")
